-- Seeded members need preferences too.
--
-- The format-aware scheduling in `draftSchedulingEmail` reads `person_preferences`
-- rows of kind 'format' to decide what Dawn proposes. Synthetic people had none, so
-- every synthetic pair fell through to "propose three times" and the in-person and
-- async branches were unreachable in testing.
--
-- `seed` rather than reusing 'manual': `people.is_synthetic` already marks the
-- cohort, but provenance on the preference row is what tells us a belief was
-- generated by a script and never held by anyone. Folding that into 'manual' —
-- which means a human curated it by hand — is exactly the kind of untrustworthy
-- provenance 0020 was written to avoid.
alter table person_preferences
  drop constraint if exists person_preferences_source_check;

alter table person_preferences
  add constraint person_preferences_source_check check (source in (
    'onboarding_chat',   -- the retired /join chat; kept for rows it produced
    'onboarding_form',   -- the multi-select questions shown after profile build
    'email_reply',
    'decline_reason',
    'manual',
    'seed'));            -- generated by src/scripts/seed.ts; never said by a person
